### ISSUE TITLE
Mark as Read Action not Firing Correctly

### ISSUE THREAD

**Issue by mttjj** [feedbin/support#550]
I have an action saved for one of my feeds to mark an article read based on the title. The action doesn't seem to fire very often. I frequently see articles matching the filter showing up in my feed. Here are some screenshots of my action settings and articles showing up that I think should be caught by the filter.
The feed is the MacStories.net RSS feed (https://www.macstories.net/feed/).

<img width="880" alt="screen shot 2016-09-17 at 3 04 58 pm" src="https://cloud.githubusercontent.com/assets/720014/18610704/b40e11c0-7ce8-11e6-8c08-7435d25a56e8.png">

![fullsizerender 3](https://cloud.githubusercontent.com/assets/720014/18610705/baeb3a18-7ce8-11e6-830e-ab317a1eb669.jpg)

![img_0050](https://cloud.githubusercontent.com/assets/720014/18610710/ce46a660-7ce8-11e6-9e63-4e3eb75cb5d2.PNG)

![fullsizerender 5](https://cloud.githubusercontent.com/assets/720014/18610707/c60ef2cc-7ce8-11e6-813c-aa60578a8061.jpg)

**Comment by Newtronic** [comment]
While I did see this issue, i have not seen it recently.  I haven't created any new rules in a while either.  I wonder if the rules engine is somewhat disconnected from the rest of the system, and takes a while to engage when a new rule is created.

**Comment by benubois** [comment]
Sorry about that! There was an issue with a server that caused actions to be unavailable. That server has been replaced and actions should be working again.

**Comment by mttjj** [comment]
I'm still seeing these articles in my feed. Either the actions server still isn't working or I have my actions set up incorrectly.
